# Use the base image ase opne JDK
FROM openjdk:11

 #Create the Argument in case you wish to Pass jar file path at CLI
# the default value  is the target directory where Jar gets generated
ARG JARFILE=target/*.jar

# Copy the Jar file
COPY ${JAR_FILE }app.jar

# Execute the command java -jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
